image: codeclou/docker-nodejs-chrome-xvfb

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  script:
  - wget https://github.com/NebulousLabs/Sia/releases/download/v1.3.3/Sia-v1.3.3-linux-amd64.zip
  - unzip Sia-v1.3.3-linux-amd64.zip
  - mv Sia-v1.3.3-linux-amd64 Sia
  - npm install
  - npm run test